version: '3.8'

volumes:
  db_value:
  static_value:
  media_value:
  postgres_data:
  redoc:

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - db_value:/var/lib/postgres/data/
    env_file:
      - ./.env

  backend:
    image: creedoffear/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: creedoffear/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./foodgramproject.crt:/etc/nginx/foodgramproject.crt
      - ./foodgramproject.key:/etc/nginx/foodgramproject.key
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always
